// src/app/components/memory/memory-game/memory-game.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { MemoryService } from 'src/app/services/memory.service';

@Component({
  selector: 'app-memory-game',
  templateUrl: './memory-game.component.html',
  styleUrls: ['./memory-game.component.scss'],
  standalone: false
})
export class MemoryGameComponent implements OnInit {

  round: number;
  blocks: number;

  showInfo = true;
  showWarning = true;

  constructor(private memory: MemoryService) { }

  ngOnInit() {
    this.restartButton();
  }

  startGameButton() {
    [this.round, this.blocks] = this.memory.startGame();
  }

  nextRoundButton() {
    [this.round, this.blocks] = this.memory.nextRound();
  }

  startRoundButton() {
    [this.round, this.blocks] = this.memory.startRound();
  }

  restartButton() {
    [this.round, this.blocks] = this.memory.restart();
  }


  // get value methods
  notCorrectValue() {
    return !this.memory.isCorrect$.value;
  }

  statusMessageValue() {
    return this.memory.statusMessage$.value;
  }

  memIntervalValue() {
    return this.memory.memInterval$.value;
  }

  isMemorisingValue() {
    return this.memory.isMemorising$.value;
  }

  closeInfo() {
    this.showInfo = false
  }

  closeWarning() {
    this.showWarning = false
  }
}

<div class="container" cdkDropListGroup>

  <div>
    <button class="button is-primary">Login</button>
    <a>&nbsp;</a>
    @if (round > 0) {
      <a>
        <button class="button is-warning" (click)="restartButton()">Restart</button>
      </a>
    }
  </div>

  <br>

    @if (showInfo) {
      <div class="notification is-info">
        Remember the sequence of blocks and build then out as it grows. Drag and drop the colour blocks to the question
        grid.
        <span class="delete" (click)="closeInfo()"></span>
      </div>
    }

    <div class="columns has-text-centered">
      <div class="column is-one-third">
        <div class="box">
          <p class="heading">Status</p>
          <p class="title">{{statusMessageValue()}}</p>
        </div>
      </div>
      <div class="column">
        @if (round > 0) {
          <div class="box">
            <div class="heading">Round</div>
            <div class="title">{{round}}</div>
          </div>
        }
      </div>
      <div class="column">
        @if (round > 0) {
          <div class="box">
            <div class="heading">Blocks</div>
            <div class="title">{{blocks}}</div>
          </div>
        }
      </div>
      <div class="column">
        @if (round > 0) {
          <div class="box">
            @if (memIntervalValue() > 0) {
              <p class="heading">Memorise Time (s)</p>
            }
            @if (memIntervalValue() <= 0) {
              <p class="heading">Penalty Time (s)</p>
            }
            <p class="title">{{memIntervalValue()}}</p>
          </div>
        }
      </div>
    </div>

    @if (round == 0) {
      <div>
        <button class="button is-primary is-large" (click)="startGameButton()">Start</button>
      </div>
    }
    @if (round > 0 && !isMemorisingValue()) {
      <div>
        <button class="button is-link is-large" (click)="nextRoundButton()">Next Round</button>
      </div>
    }
    @if (round > 0 && isMemorisingValue()) {
      <div>
        <button class="button is-success is-large" (click)="startRoundButton()">Start Round</button>
      </div>
    }
    <br>

      <app-select-grid></app-select-grid>
      <br>

        @if (round == 0) {
          <div>
            <br><app-settings></app-settings>
          </div>
        }

        <br>

          @if (round > 0) {
            <div>
              <app-memory-grid></app-memory-grid>
            </div>
          }
        </div>

// src/components/memory/MemoryGame.tsx
import React, { useState, useEffect } from 'react';
import { SelectGrid } from './SelectGrid';
import { Settings } from './Settings';
import { MemoryGrid } from './MemoryGrid';
import { useMemoryGame } from '../../hooks/useMemoryGame';

export const MemoryGame: React.FC = () => {
  const {
    round,
    blocks,
    isMemorising,
    statusMessage,
    memInterval,
    startGame,
    restart,
    nextRound,
    startRound
  } = useMemoryGame();

  const [showInfo, setShowInfo] = useState(true);

  useEffect(() => {
    if (typeof window !== 'undefined' && window.sessionStorage) {
      try {
        const val = sessionStorage.getItem('memory_builder_hide_info');
        if (val === 'true') {
          setShowInfo(false);
        }
      } catch (e) {
        console.error('Error reading info visibility state from sessionStorage', e);
      }
    }
  }, []);

  const closeInfo = () => {
    setShowInfo(false);
    if (typeof window !== 'undefined' && window.sessionStorage) {
      try {
        sessionStorage.setItem('memory_builder_hide_info', 'true');
      } catch (e) {
        console.error('Error saving info visibility state to sessionStorage', e);
      }
    }
  };

  return (
    <div className="container">
      <div className="level mb-4">
        <div className="level-left"></div>
        <div className="level-right">
          {round > 0 && (
            <button className="button is-warning is-light" onClick={restart}>
              Restart
            </button>
          )}
        </div>
      </div>

      <br />

      {showInfo && (
        <div className="notification is-info" style={{ position: 'relative' }}>
          Remember the sequence of blocks and build them out as it grows. Drag and drop the colour blocks to the question grid.
          <button className="delete" onClick={closeInfo} aria-label="close"></button>
        </div>
      )}

      <div className="columns has-text-centered">
        <div className="column is-one-third">
          <div className="box">
            <p className="heading">Status</p>
            <p className="title">{statusMessage}</p>
          </div>
        </div>
        
        {round > 0 && (
          <>
            <div className="column">
              <div className="box">
                <div className="heading">Round</div>
                <div className="title">{round}</div>
              </div>
            </div>
            
            <div className="column">
              <div className="box">
                <div className="heading">Blocks</div>
                <div className="title">{blocks}</div>
              </div>
            </div>
            
            <div className="column">
              <div className="box">
                <p className="heading">
                  {memInterval > 0 ? 'Memorise Time (s)' : 'Penalty Time (s)'}
                </p>
                <p className="title">{memInterval}</p>
              </div>
            </div>
          </>
        )}
      </div>

      <div className="has-text-centered mb-5">
        {round === 0 && (
          <button className="button is-primary is-large" onClick={startGame}>
            Start
          </button>
        )}
        {round > 0 && !isMemorising && (
          <button className="button is-link is-large" onClick={nextRound}>
            Next Round
          </button>
        )}
        {round > 0 && isMemorising && (
          <button className="button is-success is-large" onClick={startRound}>
            Start Round
          </button>
        )}
      </div>

      <div className="is-flex is-justify-content-start">
        <SelectGrid />
      </div>

      <br />

      {round === 0 && (
        <div>
          <br />
          <Settings />
        </div>
      )}

      <br />

      {round > 0 && (
        <div className="is-flex is-justify-content-start">
          <MemoryGrid />
        </div>
      )}
    </div>
  );
};
export default MemoryGame;
