// src/app/components/memory/settings/settings.component.ts
import { Component, OnInit } from '@angular/core';
import { MemoryService } from 'src/app/services/memory.service';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.scss'],
  standalone: false
})
export class SettingsComponent implements OnInit {

  startGrid = this.memory.startGrid$.value;
  increaseGrid = this.memory.increaseGrid$.value;
  colourSelect = this.memory.colourSelect$.value;
  roundTime = this.memory.roundTime$.value;
  penaltyTime = this.memory.penaltyTime$.value;

  constructor(private memory: MemoryService) { }

  ngOnInit() {
  }

  changeStartGrid(e) {
    this.memory.startGrid$.next(e.value);
  }

  changeIncreaseGrid(e) {
    this.memory.increaseGrid$.next(e.value);
  }

  changeColourSelect(e) {
    this.memory.colourSelect$.next(e.value);
  }

  changeRoundTime(e) {
    this.memory.roundTime$.next(e.value);
  }

  changePenaltyTime(e) {
    this.memory.penaltyTime$.next(e.value);
  }

}

<div class="box">
    <p class="heading">Settings</p>

    <div>Number of blocks to start with: {{startGrid}}</div><br>

    <app-slider [(ngModel)]="startGrid" [min]=3 [max]=110 [step]=1 [style]="{'width':'15em'}"
        (onChange)="changeStartGrid($event)"></app-slider><br>

    <div>Number of blocks to increase after every round: {{increaseGrid}}</div><br>

    <app-slider [(ngModel)]="increaseGrid" [min]=1 [max]=5 [step]=1 [style]="{'width':'15em'}"
        (onChange)="changeIncreaseGrid($event)"></app-slider><br>

    <div>Number of colours to use: {{colourSelect}}</div><br>

    <app-slider [(ngModel)]="colourSelect" [min]=3 [max]=8 [step]=1 [style]="{'width':'15em'}"
        (onChange)="changeColourSelect($event)"></app-slider><br>

    <div>Memorising time added after each round: {{roundTime}}</div><br>

    <app-slider [(ngModel)]="roundTime" [min]=1 [max]=7 [step]=1 [style]="{'width':'15em'}"
        (onChange)="changeRoundTime($event)"></app-slider><br>

    <div>Memorising penalty time reduced after incorrect answer: {{penaltyTime}}</div><br>

    <app-slider [(ngModel)]="penaltyTime" [min]=1 [max]=3 [step]=1 [style]="{'width':'15em'}"
        (onChange)="changePenaltyTime($event)"></app-slider><br>
</div>

// src/components/memory/Settings.tsx
import React from 'react';
import { Slider } from '../shared/Slider';
import { useMemoryGame } from '../../hooks/useMemoryGame';

export const Settings: React.FC = () => {
  const {
    startGrid,
    setStartGrid,
    increaseGrid,
    setIncreaseGrid,
    colourSelect,
    setColourSelect,
    roundTime,
    setRoundTime,
    penaltyTime,
    setPenaltyTime
  } = useMemoryGame();

  return (
    <div className="box">
      <p className="heading">Settings</p>

      <div>Number of blocks to start with: {startGrid}</div><br />
      <Slider
        value={startGrid}
        min={3}
        max={110}
        step={1}
        onChange={setStartGrid}
      /><br />

      <div>Number of blocks to increase after every round: {increaseGrid}</div><br />
      <Slider
        value={increaseGrid}
        min={1}
        max={5}
        step={1}
        onChange={setIncreaseGrid}
      /><br />

      <div>Number of colours to use: {colourSelect}</div><br />
      <Slider
        value={colourSelect}
        min={3}
        max={8}
        step={1}
        onChange={setColourSelect}
      /><br />

      <div>Memorising time added after each round: {roundTime}</div><br />
      <Slider
        value={roundTime}
        min={1}
        max={7}
        step={1}
        onChange={setRoundTime}
      /><br />

      <div>Memorising penalty time reduced after incorrect answer: {penaltyTime}</div><br />
      <Slider
        value={penaltyTime}
        min={1}
        max={3}
        step={1}
        onChange={setPenaltyTime}
      /><br />
    </div>
  );
};
