// MemoryBuilder/memorybuilder-app/src/app/components/countdown/countdown.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-countdown',
  templateUrl: './countdown.component.html',
  styleUrls: ['./countdown.component.scss']
})
export class CountdownComponent implements OnInit {

  countDays: string;
  countHours: string;
  countMinutes: string;
  countSeconds: string;
  dateTarget: Date;
  interval: any;

  constructor() { }

  ngOnInit() {
    this.dateTarget = new Date('7 January, 2019 12:00');
    this.setCountDown(); // to have output values oninit

    this.interval = setInterval(() => {
      this.setCountDown();
    }, 1000);
  }

  setCountDown() {

    let today = new Date();
    let dateDifference = this.dateTarget.valueOf() - today.valueOf();

    let day = Math.trunc(dateDifference / (1000 * 60 * 60 * 24));
    let rem = dateDifference % (1000 * 60 * 60 * 24);

    let hours = Math.trunc(rem / (1000 * 60 * 60));
    rem = rem % (1000 * 60 * 60);

    let min = Math.trunc(rem / (1000 * 60));
    rem = rem % (1000 * 60);

    let sec = Math.trunc(rem / 1000);

    this.countDays = day.toString();
    this.countHours = hours.toString();
    this.countMinutes = min.toString();
    this.countSeconds = sec.toString();
  }

}

// src/components/countdown/Countdown.tsx
import React, { useState, useEffect } from 'react';

export const Countdown: React.FC = () => {
  const [countDays, setCountDays] = useState('');
  const [countHours, setCountHours] = useState('');
  const [countMinutes, setCountMinutes] = useState('');
  const [countSeconds, setCountSeconds] = useState('');

  const dateTarget = new Date('31 January, 2019 12:00');

  const setCountDown = () => {
    const today = new Date();
    const dateDifference = dateTarget.valueOf() - today.valueOf();

    const day = Math.trunc(dateDifference / (1000 * 60 * 60 * 24));
    let rem = dateDifference % (1000 * 60 * 60 * 24);

    const hours = Math.trunc(rem / (1000 * 60 * 60));
    rem = rem % (1000 * 60 * 60);

    const min = Math.trunc(rem / (1000 * 60));
    rem = rem % (1000 * 60);

    const sec = Math.trunc(rem / 1000);

    setCountDays(day.toString());
    setCountHours(hours.toString());
    setCountMinutes(min.toString());
    setCountSeconds(sec.toString());
  };

  useEffect(() => {
    setCountDown(); // run once immediately

    const interval = setInterval(() => {
      setCountDown();
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  return (
    <p>
      Extend your mind in: {countDays} days {countHours} hours {countMinutes} minutes {countSeconds} seconds
    </p>
  );
};
export default Countdown;
