// src/App.tsx
import React from 'react';
import { MemoryGame } from './components/memory/MemoryGame';
import memoryBuilderIcon from './assets/images/memory-builder-icon.png';
import { version } from '../package.json';

export const App: React.FC = () => {

  return (
    <div className="container">
      <section className="section">
        <div className="container has-text-centered">
          <h1 className="title">Welcome to Memory Builder</h1>
          <h2 className="subtitle">Extend Your Memory</h2>

          <img 
            src={memoryBuilderIcon} 
            alt="Memory Builder Icon" 
            style={{ maxWidth: '120px', height: 'auto' }}
          />
          <br />
        </div>
      </section>

      <MemoryGame />

      <br />
      <footer className="footer">
        <div className="content has-text-centered">
          <p>With ❤️ for my Mom</p>
          <p>Version {version}</p>
        </div>
      </footer>
    </div>
  );
};

export default App;

// src/app/app.component.ts
import { Component } from '@angular/core';
import packageJson from '../../package.json';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  standalone: false
})
export class AppComponent {
  title = 'Memory Builder';
  version = packageJson.version;
}

<div class="container">
    <section class="section">
        <div class="container has-text-centered">

            <h1 class="title">Welcome to Memory Builder</h1>
            <h2 class="subtitle">Extend Your Memory</h2>

            <img src="../assets/images/memory-builder-icon.png" />

            <br>
            <router-outlet></router-outlet>
        </div>
    </section>

    <app-memory-game></app-memory-game>

    <br>
    <footer class="footer">
        <div>Powered by <a href="https://schalk.heerden.com" target="_blank">Heerden.com</a></div>
        <div><a href="https://github.com/heerden/memory-builder" target="_blank">Angular code on Github</a></div>
        <div>Version {{version}}</div>
    </footer>
</div>
